# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  lint:
    desc: Run linting
    cmds:
      - golangci-lint run 
    sources:
      - "*.go"

  test:
    desc: Runs tests on Go code.
    cmds:
      - go test ./..
    sources:
      - "*.go"

  build:
    desc: Compiles the Go code.
    cmds:
      - go build .
    sources:
      - "*.go"