# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - cmd: dev
    silent: true

  lint:
    desc: Run linting
    cmds:
      - golangci-lint run
    sources:
      - "*.go"

  test:
    desc: Runs tests on Go code.
    cmds:
      - go test .
    sources:
      - "*.go"

  dev:
    desc: Quick alias to run all dev related tasks.
    cmds:
      - task: lint
      - task: lint
      - task: run

  run:
    desc: Runs the Go code.
    cmds:
      - go run . {{.CLI_ARGS}}

  build:
    desc: Compiles the Go code.
    cmds:
      - go build .
    sources:
      - "*.go"
