# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: dev
    silent: true

  lint:
    desc: Run linting
    cmds:
      - golangci-lint run
    sources:
      - "*.go"

  test:
    desc: Runs tests on Go code.
    cmds:
      - go test ./... -cover
    sources:
      - "*.go"

  dev:
    desc: Quick alias to run all dev related tasks.
    cmds:
      - task: lint
      - task: test
      - task: run

  run:
    desc: Runs the Go code.
    cmds:
      - go run . {{.CLI_ARGS}}

  build:
    desc: Compiles the Go code.
    cmds:
      - go build .
    sources:
      - "*.go"

  test-release:
    desc: Runs Goreleaser in snapshot mode.
    aliases:
      - tr
    cmds:
      - goreleaser check
      - goreleaser healthcheck
      - goreleaser release --snapshot --clean
    sources:
      - "*.go"

  release:
    desc: Runs Goreleaser in release mode.
    vars:
      VERSION: "v1.0.0" 
    aliases:
      - r
    cmds:
      - goreleaser check
      - goreleaser healthcheck
      - git tag -a {{.VERSION}} -m "Release {{.VERSION}}"
      - git push origin {{.VERSION}}
      - goreleaser release --clean
    sources:
      - "*.go"